---
title: "Live 06 - Data Transformation"
author: "Sutiwas"
date: "2024-07-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Live 06 - Data Transformation

## Load libraries

```{r Load libraries}
library(tidyverse)
library(RSQLite)
library(glue)
library(RPostgreSQL)
library(lubridate)
library(sqldf)
library(jsonlite)
```

## library glue

```{r library glue}
# library glue -> to glue messages
my_name <- "toy"
my_age <- 35

glue("Hi my name is {my_name}. Today I'm {my_age} years old.")
```

------------------------------------------------------------------------

## library tidyverse

```{r library tidyverse}
# library tidyverse
# data transformation => dplyr

# 1. select
# 2. filter
# 3. arrange 
# 4. mutate => create new column
# 5. summarise

carnames <- rownames(mtcars)
view(mtcars)

# pipeline
select(mtcars, mpg, hp, wt)

m2 <- mtcars %>%
  select(mpg, hp, wt) %>%
  filter(hp > 200) %>%
  arrange(mpg) %>%
  head()

head(arrange(filter(select(mtcars, mpg, hp, wt), hp > 200), mpg))

# filter am == 0
# grep can return character value and normally return the index of said value 
# but grepl() will always return logic value
mtcars %>%
  select(model, mpg, hp, wt, am) %>%
  filter(am == 0 & grepl("^M", model)) %>%
  arrange(am, desc(hp))

m3 <- mtcars %>%
  select(model, mpg, hp, wt, am) %>%
  filter(between(hp, 100, 200)) %>%
  arrange(am, desc(hp))

# write csv file
write_csv(m3, "result.csv")

# mutate to create new columns
mtcars %>%
  filter(mpg >= 20) %>%
  select(model, mpg, hp, wt, am) %>%
  mutate(new_col = "Data Rockie",
         hp_halve = hp/2,
         ## =IF(am==0,"auto", "manual")
         am_label = if_else(am==0,"auto", "manual"))

# summarise, summarize
  # aggregate function in SQL
m4 <- mtcars %>%
  mutate(am = if_else(am==0, "auto", "manual")) %>%
  group_by(am) %>%
  summarise(avg_mpg = mean(mpg),
            med_mpg = median(mpg),
            sum_mpg = sum(mpg),
            max_mpg = max(mpg),
            max_hp = max(hp),
            min_hp = min(hp),
            # spread
            n = n(),
            # var_hp = var(hp),
            # sd_hp = sd(hp)
            )

write_csv(m4, "sum_m4.csv")

## join in R
left_join(band_members, band_instruments, by = "name")
inner_join(band_members, band_instruments, by = "name")
full_join(band_members, band_instruments, by = "name")

m5 <- band_members %>%
  select(member_name = name,
         band_name = band) %>%
  left_join(band_instruments,
            by = c("member_name" = "name"))

## random sampling
# pull() pull column values only in a vector
mtcars %>%
  sample_n(5) %>%
  pull(model)

mtcars %>%
  # sample_frac(0.20) %>%
  summarise(avg_hp = mean(hp))

## summary
## 100% => Analytics
## 20% => Statistics

## count
mtcars <- mtcars %>%
  mutate(am = if_else(am==0, 
                      "Auto", 
                      "Manual"))
```

------------------------------------------------------------------------

## library sqldf

```{r sqldf}
# sqldf("
#       SELECT
#             mpg,
#             hp
#       FROM mtcars
#       WHERE hp >= 200")
# 
# sqldf(
#   "select avg(hp), max(hp), count(*) from mtcars"
# )
```

------------------------------------------------------------------------

## library RPostgreSQL & RSQLite & tidyverse

```{r library(RPostgreSQL), library(RSQLite), library(tidyverse)}
## create connection to sqlite.db file
con <- dbConnect(SQLite(), "C:/Online Learning/DataRockie Bootcamp/DataRockie Bootcamp 10th/R Programming/data/chinook/chinook.db")

## list tables
dbListTables(con)

## list fields/ columns
dbListFields(con, "customers")

## get data from database tables
usa <- dbGetQuery(con, "
  select 
    firstname, 
    lastname, 
    country, 
    email
  from customers
  where country = 'USA' ")

## create dataframe 
products <- tribble(
  ~id, ~product_name,
  1, "chocolate",
  2, "pineapple",
  3, "samsung galaxy s23"
  )

## write table to database
dbWriteTable(con, "products", products)

## remove table
dbRemoveTable(con, "products")

## close connection
dbDisconnect(con)
```

------------------------------------------------------------------------

## RPostgreSQL and tidyverse

```{r library(RPostgreSQL), library(tidyverse)}
## connect to PostgreSQL server
## create connection to elephantsql.com after building a database
# these parameters below are used as connector
con <- dbConnect(
  PostgreSQL(),
  host = "arjuna.db.elephantsql.com",
  dbname = "hcmsanst",
  user = "hcmsanst",
  password = "n9MIT1wNqy6HG5HsO-ypvf8SLD4VfMCh",
  port = 5432
)

## db List Tables
dbListTables(con)

dbWriteTable(con, "products", products)

## get data
df <- dbGetQuery(con, "select id, product_name from products")
```

------------------------------------------------------------------------

## JSON

```{r JSON}
## how to read a json file
my_profile <- fromJSON("../data/my_profile.json")
my_profile
```
